.include "include/beatscript.inc"
.include "games/marching_orders/macros.inc"

load_marching_orders_labels



.section .script.sub
@ Marching Orders - Subroutines

script marching_orders_sub_08a83758
if_localized
    rest 18
    marching_orders_play_voice_sfx VOICE_ATTENTION
    rest 6
    marching_orders_play_voice_sfx VOICE_ATTENTION_2
    marching_orders_event01
    clear_text_f
    rest 9
    marching_orders_play_voice_sfx VOICE_ATTENTION_3
    rest 15
    rest 24
else
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_ATTENTION
    rest 24
    rest 24
end_if
return

script marching_orders_sub_08a83758beatstop
    rest 18
    marching_orders_play_voice_sfx VOICE_ATTENTION
    rest 6
    marching_orders_play_voice_sfx VOICE_ATTENTION_2
    marching_orders_event00 256
    marching_orders_event01
    clear_text_f
    rest 9
    marching_orders_play_voice_sfx VOICE_ATTENTION_3
    rest 15
    rest 24
return

script marching_orders_sub_08a837ac
if_localized
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_MARCH
    #ifdef PLUS
    print_text_f D_0805c8e3
    #endif
    rest 24
    marching_orders_play_voice_sfx SHOUT_START
    marching_orders_event00 263
    spawn_cue CUE_STEP
    beat_anim
else
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_MARCH
    #ifdef PLUS
    print_text_f D_0805c8e3
    #endif
    rest 24
    marching_orders_play_voice_sfx SHOUT_START
    marching_orders_event00 263
    spawn_cue CUE_STEP
    beat_anim
    rest 24
end_if
return

script marching_orders_sub_08a83848
if_localized
    call marching_orders_sub_08a83758
    call marching_orders_sub_08a837ac
    rest 24
else
    call marching_orders_sub_08a83758
    call marching_orders_sub_08a837ac
end_if
return

script marching_orders_sub_08a83848_nobeat
    call marching_orders_sub_08a83758
    call marching_orders_sub_08a837ac
return

script marching_orders_sub_08a83848_beatstop
    call marching_orders_sub_08a83758beatstop
    call marching_orders_sub_08a837ac
    rest 24
return

script marching_orders_sub_08a83848_beatstop_nobeat
    call marching_orders_sub_08a83758beatstop
    call marching_orders_sub_08a837ac
return

script marching_orders_sub_08a8386c
    clear_text_f
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
return

script marching_orders_sub_08a8386c_nobeat
    clear_text_f
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
return

script marching_orders_sub_08a8386c_noclear
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
return

script marching_orders_sub_08a83998
if_localized
    rest 18
    marching_orders_play_voice_sfx VOICE_ATTENTION
    rest 6
    clear_text_f
    marching_orders_event01
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    marching_orders_play_voice_sfx VOICE_ATTENTION_2
    rest 9
    marching_orders_play_voice_sfx VOICE_ATTENTION_3
    rest 15
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_HALT
    #ifdef PLUS
    print_text_f D_0805c8e4
    #endif
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_HALT
    beat_anim
    rest 24
    marching_orders_play_voice_sfx SHOUT_STOP
    marching_orders_event00 1
    play_sfx s_guntai_foot2_seqData
    rest 24
    clear_text_f
else
    clear_text_f
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_ATTENTION
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_HALT
    #ifdef PLUS
    print_text_f D_0805c8e4
    #endif
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_HALT
    beat_anim
    rest 24
    marching_orders_play_voice_sfx SHOUT_STOP
    marching_orders_event00 1
    play_sfx s_guntai_foot2_seqData
    rest 24
    clear_text_f
end_if
return

script marching_orders_sub_08a83998_nobeat
    rest 18
    marching_orders_play_voice_sfx VOICE_ATTENTION
    rest 6
    clear_text_f
    marching_orders_event01
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    marching_orders_play_voice_sfx VOICE_ATTENTION_2
    rest 9
    marching_orders_play_voice_sfx VOICE_ATTENTION_3
    rest 15
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_HALT
    #ifdef PLUS
    print_text_f D_0805c8e4
    #endif
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_HALT
    beat_anim
    rest 24
    marching_orders_play_voice_sfx SHOUT_STOP
    marching_orders_event00 1
    play_sfx s_guntai_foot2_seqData
return

script marching_orders_sub_08a83b24
if_localized
    rest 18
    marching_orders_play_voice_sfx VOICE_ATTENTION
    rest 6
    marching_orders_event01
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    clear_text_f
    marching_orders_play_voice_sfx VOICE_ATTENTION_2
    rest 9
    marching_orders_play_voice_sfx VOICE_ATTENTION_3
    rest 15
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    call marching_orders_sub_08a8386c
else
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_ATTENTION
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    call marching_orders_sub_08a8386c
end_if
return

script marching_orders_sub_08a83bfc
if_localized
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_HALT
    #ifdef PLUS
    print_text_f D_0805c8e4
    #endif
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_HALT
    beat_anim
    rest 24
    marching_orders_play_voice_sfx SHOUT_STOP
    marching_orders_event00 1
    play_sfx s_guntai_foot2_seqData
    rest 24
    clear_text_f
else
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_HALT
    #ifdef PLUS
    print_text_f D_0805c8e4
    #endif
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_HALT
    beat_anim
    rest 24
    marching_orders_play_voice_sfx SHOUT_STOP
    marching_orders_event00 1
    play_sfx s_guntai_foot2_seqData
    rest 24
    clear_text_f
end_if
return

script marching_orders_2_sub_08a83cc8
if_localized
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 11
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE_2
    rest 13
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_RIGHT
    #ifdef PLUS
    print_text_f D_0805c8e1
    #endif
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    no_op
    spawn_cue CUE_TURN_RIGHT
    beat_anim
    rest 24
    marching_orders_event00 4
    marching_orders_play_voice_sfx SHOUT_TURN
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    clear_text_f
else
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_RIGHT
    #ifdef PLUS
    print_text_f D_0805c8e1
    #endif
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    no_op
    spawn_cue CUE_TURN_RIGHT
    beat_anim
    rest 24
    marching_orders_event00 4
    marching_orders_play_voice_sfx SHOUT_TURN
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    clear_text_f
end_if
return

script marching_orders_2_sub_08a83ea8
if_localized
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_LEFT_FACE
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 11
    marching_orders_play_voice_sfx VOICE_LEFT_FACE_2
    rest 13
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_LEFT
    #ifdef PLUS
    print_text_f D_0805c8e2
    #endif
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    no_op
    spawn_cue CUE_TURN_LEFT
    beat_anim
    rest 24
    marching_orders_event00 3
    marching_orders_play_voice_sfx SHOUT_TURN
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    clear_text_f
else
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_LEFT_FACE
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_LEFT
    #ifdef PLUS
    print_text_f D_0805c8e2
    #endif
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    no_op
    spawn_cue CUE_TURN_LEFT
    beat_anim
    rest 24
    marching_orders_event00 3
    marching_orders_play_voice_sfx SHOUT_TURN
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    clear_text_f
end_if
return

script marching_orders_2_sub_08a84088
if_localized
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE_F
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 11
    marching_orders_play_voice_sfx VOICE_F_FACE_RIGHT
    rest 13
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_RIGHT
    #ifdef PLUS
    print_text_f D_0805c8e1
    #endif
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    no_op
    spawn_cue CUE_TURN_RIGHT
    beat_anim
    rest 24
    marching_orders_event00 4
    marching_orders_play_voice_sfx SHOUT_TURN
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
else
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE_F
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_RIGHT
    #ifdef PLUS
    print_text_f D_0805c8e1
    #endif
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    no_op
    spawn_cue CUE_TURN_RIGHT
    beat_anim
    rest 24
    marching_orders_event00 4
    marching_orders_play_voice_sfx SHOUT_TURN
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    clear_text_f
end_if
return

script marching_orders_2_sub_08a84268
if_localized
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_LEFT_FACE_F
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 11
    marching_orders_play_voice_sfx VOICE_F_FACE_LEFT
    rest 13
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_LEFT
    #ifdef PLUS
    print_text_f D_0805c8e2
    #endif
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    no_op
    spawn_cue CUE_TURN_LEFT
    beat_anim
    rest 24
    marching_orders_event00 3
    marching_orders_play_voice_sfx SHOUT_TURN
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    clear_text_f
else
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_LEFT_FACE_F
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_LEFT
    #ifdef PLUS
    print_text_f D_0805c8e2
    #endif
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    no_op
    spawn_cue CUE_TURN_LEFT
    beat_anim
    rest 24
    marching_orders_event00 3
    marching_orders_play_voice_sfx SHOUT_TURN
    marching_orders_event00 8
    play_sfx s_guntai_foot1_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    marching_orders_event00 7
    play_sfx s_guntai_foot2_seqData
    spawn_cue CUE_STEP
    beat_anim
    rest 24
    clear_text_f
end_if
return

script marching_orders_sub_08a84448
if_localized
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE
    rest 11
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE_2
    rest 13
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_RIGHT
    #ifdef PLUS
    print_text_f D_0805c8e1
    #endif
    spawn_cue CUE_TURN_RIGHT
    beat_anim
    rest 24
    marching_orders_event00 4
    marching_orders_play_voice_sfx SHOUT_TURN
    rest 24
    clear_text_f
else
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE
    rest 24
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_RIGHT
    #ifdef PLUS
    print_text_f D_0805c8e1
    #endif
    spawn_cue CUE_TURN_RIGHT
    beat_anim
    rest 24
    marching_orders_event00 4
    marching_orders_play_voice_sfx SHOUT_TURN
    rest 24
    clear_text_f
end_if
return

script marching_orders_sub_08a84448_nobeat
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE
    rest 11
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE_2
    rest 13
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_RIGHT
    #ifdef PLUS
    print_text_f D_0805c8e1
    #endif
    spawn_cue CUE_TURN_RIGHT
    beat_anim
    rest 24
    marching_orders_event00 4
    marching_orders_play_voice_sfx SHOUT_TURN
return

script marching_orders_sub_08a8452c
if_localized
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_LEFT_FACE
    rest 11
    marching_orders_play_voice_sfx VOICE_LEFT_FACE_2
    rest 13
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_LEFT
    #ifdef PLUS
    print_text_f D_0805c8e2
    #endif
    spawn_cue CUE_TURN_LEFT
    beat_anim
    rest 24
    marching_orders_event00 3
    marching_orders_play_voice_sfx SHOUT_TURN
else
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_LEFT_FACE
    rest 24
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_LEFT
    #ifdef PLUS
    print_text_f D_0805c8e2
    #endif
    spawn_cue CUE_TURN_LEFT
    beat_anim
    rest 24
    marching_orders_event00 3
    marching_orders_play_voice_sfx SHOUT_TURN
    rest 24
    clear_text_f
end_if
return

script marching_orders_2_sub_08a84610
if_localized
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE_F
    rest 11
    marching_orders_play_voice_sfx VOICE_F_FACE_RIGHT
    rest 13
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_RIGHT
    #ifdef PLUS
    print_text_f D_0805c8e1
    #endif
    spawn_cue CUE_TURN_RIGHT
    beat_anim
    rest 24
    marching_orders_event00 4
    marching_orders_play_voice_sfx SHOUT_TURN
    rest 24
    clear_text_f
else
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE_F
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_RIGHT
    #ifdef PLUS
    print_text_f D_0805c8e1
    #endif
    spawn_cue CUE_TURN_RIGHT
    beat_anim
    rest 24
    marching_orders_event00 4
    marching_orders_play_voice_sfx SHOUT_TURN
    rest 24
    clear_text_f
    rest 24
end_if
return

script marching_orders_2_sub_08a84610_nobeat
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE_F
    rest 11
    marching_orders_play_voice_sfx VOICE_F_FACE_RIGHT
    rest 13
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_RIGHT
    #ifdef PLUS
    print_text_f D_0805c8e1
    #endif
    spawn_cue CUE_TURN_RIGHT
    beat_anim
    rest 24
    marching_orders_event00 4
    marching_orders_play_voice_sfx SHOUT_TURN
    rest 24
    clear_text_f
return

script marching_orders_unk_sub_08a846f4
if_localized
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_LEFT_FACE_F
    rest 11
    marching_orders_play_voice_sfx VOICE_F_FACE_LEFT
    rest 13
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_LEFT
    #ifdef PLUS
    print_text_f D_0805c8e1
    #endif
    spawn_cue CUE_TURN_LEFT
    beat_anim
    rest 24
    marching_orders_event00 3
    marching_orders_play_voice_sfx SHOUT_TURN
    rest 24
    clear_text_f
    rest 24
else
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_LEFT_FACE_F
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_LEFT
    #ifdef PLUS
    print_text_f D_0805c8e1
    #endif
    spawn_cue CUE_TURN_LEFT
    beat_anim
    rest 24
    marching_orders_event00 3
    marching_orders_play_voice_sfx SHOUT_TURN
    rest 24
    clear_text_f
    rest 24
end_if
return

script marching_orders_2_sub_08a847d8
if_localized
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE_F
    rest 11
    marching_orders_play_voice_sfx VOICE_F_FACE_RIGHT
    rest 13
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_RIGHT
    #ifdef PLUS
    print_text_f D_0805c8e1
    #endif
    spawn_cue CUE_TURN_RIGHT
    beat_anim
    rest 24
    marching_orders_event00 4
    marching_orders_play_voice_sfx SHOUT_TURN
    rest 24
    clear_text_f
else
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_RIGHT_FACE_F
    rest 24
    marching_orders_event01
    marching_orders_play_voice_sfx VOICE_TURN_RIGHT
    #ifdef PLUS
    print_text_f D_0805c8e1
    #endif
    spawn_cue CUE_TURN_RIGHT
    beat_anim
    rest 24
    marching_orders_event00 4
    marching_orders_play_voice_sfx SHOUT_TURN
    rest 24
    clear_text_f
end_if
return

.end
