.include "include/beatscript.inc"
.include "games/rap_men/macros.inc"



.section .script.entry
@ Rap Women - Script Entry Point

script script_rap_women_entry
    set_tempo 124
    rest 24
    call script_rap_women_prologue
    set_game_fade_in_time 16
    load_rap_women
    enable_play_inputs
    start_tracking_inputs
    call script_rap_women_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_rap_women, script_rap_women_entry



.section .script.prologue
@ Rap Women - Prologue

script script_rap_women_prologue
    set_game_fade_in_time 8
    load_game rap_women_prologue_engine, 0
    run stop_all_soundplayers
    play_sfx s_jingle_rap_seqData
    rest 24
    rest 24
    run func_08047138, 0
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    run func_08006d80, 0
    rest 24
    set_game_fade_in_time 16
return



.section .script.main
@ Rap Women - Text

text text_rap_women_juji_desu_ka
    .asciz ".b:1‚h‚”f‚“@‚P‚O@‚`‚lC@.b:0‚ˆ‚•‚ˆH.8:1"
endtext

text text_rap_women_oyatsu_desu_ka
    .asciz ".b:1‚h‚”f‚“@‚“‚‚‚ƒ‚‹@‚”‚‰‚‚…C@.b:0‚ˆ‚•‚ˆH.8:1"
endtext

text text_rap_women_naisho_desu_ka
    .asciz ".b:1‚v‚ˆ‚f‚“@‚”‚@‚‹‚‚‚—C@.b:0‚ˆ‚•‚ˆH.8:1"
endtext

text text_rap_women_kare_no_oyatsu_da_ne
    .asciz ".9:1‚s‚ˆ‚…‚“‚…@‚‚’‚…@‚‚Œ‚Œ@‚”‚ˆ‚…‚‰‚’@‚“‚‚‚ƒ‚‹‚“C.9:0@‚™‚@‚“‚…‚…H.8:1"
endtext

text text_rap_women_tabeteii_kamo_ne
    .asciz ".9:1‚d‚‚”@f‚…‚@‚‚Œ‚Œ@‚•‚C@.9:0‚™‚@‚†‚…‚…‚Œ@‚‚…H.8:1"
endtext

text text_rap_women_aketeii_kamo_ne
    .asciz ".9:1‚n‚‚…‚@f‚…‚@‚•‚C@.9:0‚™‚@‚†‚…‚…‚Œ@‚‚…H.8:1"
endtext

text text_rap_women_oyatsu_wa_saikou
    .asciz ".a:1‚r‚‚‚ƒ‚‹‚‰‚‚‡@‚‰‚“@.a:0‚“‚@‚`‚v‚d‚r‚n‚l‚dI.8:1"
endtext

text text_rap_women_kibun_wa_saikou
    .asciz ".a:1‚h@‚†‚…‚…‚Œ@.a:0‚“‚@‚`‚v‚d‚r‚n‚l‚dI.8:1"
endtext

text text_rap_women_amakute_saikou
    .asciz ".a:1‚r‚—‚…‚…‚”‚“@‚‚’‚…@.a:0‚“‚@‚`‚v‚d‚r‚n‚l‚dI.8:1"
endtext

text text_rap_women_betsubara_saikou
    .asciz ".a:1‚b‚‚‹‚…‚“@‚‚’‚…@.a:0‚“‚@‚`‚v‚d‚r‚n‚l‚dI.8:1"
endtext

text text_rap_women_kare_ni_wa_naisho
    .asciz ".a:1‚b‚Œ‚•‚…‚Œ‚…‚“‚“@‚”‚ˆ‚‚”@‚—‚…@.a:0‚r‚s‚n‚k‚d@f‚d‚lI.8:1"
endtext

text text_rap_women_dare_ni_mo_naisho
    .asciz ".a:1‚s‚…‚Œ‚Œ@f‚…‚@‚—‚…@‚‚’‚…@.a:0‚k‚n‚`‚s‚g‚r‚n‚l‚dI.8:1"
endtext



@ Rap Women - Marking Criteria

struct rap_women_marking_criteria_0
    /* Positive Remark */     .word D_08067ca4
    /* Negative Remark */     .word D_08067c80
    /* Flags */               .hword CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES
    /* Pos: Required Hits */  .hword 0xCC @ 80%
    /* Neg: Minimum Hits */   .hword 0x66 @ 40%
    /* Neg: Maximum Misses */ .hword 0x33 @ 20%
endstruct

struct rap_women_marking_criteria_1
    /* Positive Remark */     .word D_08067cf4
    /* Negative Remark */     .word D_08067ccc
    /* Flags */               .hword CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES
    /* Pos: Required Hits */  .hword 0xCC @ 80%
    /* Neg: Minimum Hits */   .hword 0x66 @ 40%
    /* Neg: Maximum Misses */ .hword 0x33 @ 20%
endstruct

struct rap_women_marking_criteria_2
    /* Positive Remark */     .word D_08067d44
    /* Negative Remark */     .word D_08067d18
    /* Flags */               .hword CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES
    /* Pos: Required Hits */  .hword 0xCC @ 80%
    /* Neg: Minimum Hits */   .hword 0x66 @ 40%
    /* Neg: Maximum Misses */ .hword 0x33 @ 20%
endstruct

struct rap_women_marking_criteria
    .word rap_women_marking_criteria_0
    .word rap_women_marking_criteria_1
    .word rap_women_marking_criteria_2
    .word END_OF_CRITERIA
endstruct



@ Rap Women - Main Script

script script_rap_women_main
    set_results_header D_08067d70
    import_marking_criteria rap_women_marking_criteria
    run gameplay_set_mercy_count, 1
    start_tracking_inputs
    rest 24
    enable_pause_menu
    rest 24
    set_tempo 180
    set_music_volume 256
    start_perfect_campaign
    print_text_f D_08067d84
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    clear_text_f
    rest 24
    rest 24
    set_marking_criteria 0
    print_text_f text_rap_women_oyatsu_desu_ka
    play_sfx_localized s_f_rapW_v_YoOyatuDesuka_seqData, s_f_rapW_v_YoOyatuDesuka_en_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    rest 16
    play_music s_rap_jazz_bgm_seqData
    rest 8
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 22
    set_marking_criteria 0
    print_text_f text_rap_women_juji_desu_ka
    play_sfx_localized s_f_rapW_v_Yo10JiDesuka_seqData, s_f_rapW_v_Yo10JiDesuka_en_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    rest 2
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 22
    set_marking_criteria 0
    print_text_f text_rap_women_oyatsu_desu_ka
    play_sfx_localized s_f_rapW_v_YoOyatuDesuka_seqData, s_f_rapW_v_YoOyatuDesuka_en_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest_localized 26, 17
    play_sfx_localized s_f_rapW_v_OyatuwaSaiko_seqData, s_f_rapW_v_OyatuwaSaiko_en_seqData
    rest_localized 0, 9
    set_marking_criteria 2
    print_text_f text_rap_women_oyatsu_wa_saikou
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    spawn_cue CUE_UUN
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_women_amakute_saikou
    play_sfx_localized s_f_rapW_v_AmakuteSaiko_seqData, s_f_rapW_v_AmakuteSaiko_en_seqData
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    spawn_cue CUE_UUN
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_women_kibun_wa_saikou
    play_sfx_localized s_f_rapW_v_KibunnwaSaiko_seqData, s_f_rapW_v_KibunnwaSaiko_en_seqData
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    spawn_cue CUE_UUN
    clear_text_f
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 0
    print_text_f text_rap_women_naisho_desu_ka
    beat_anim
    rest 24
    rest 12
    rest 6
    play_sfx_localized s_f_rapW_v_Naishodesuka_seqData, s_f_rapW_v_Naishodesuka_en_seqData
    rap_men_animate_rapper ANIM_HONTO
    rest 6
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 0
    print_text_f text_rap_women_juji_desu_ka
    play_sfx_localized s_f_rapW_v_Yo10JiDesuka_seqData, s_f_rapW_v_Yo10JiDesuka_en_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 1
    print_text_f text_rap_women_kare_no_oyatsu_da_ne
    play_sfx_localized s_f_rapW_v_KarenoOyatudane_seqData, s_f_rapW_v_KarenoOyatudane_en_seqData
    rap_men_animate_rapper ANIM_HONTO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    clear_text_f
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 1
    print_text_f text_rap_women_aketeii_kamo_ne
    play_sfx_localized s_f_rapW_v_AketeIikamone_seqData, s_f_rapW_v_AketeIikamone_en_seqData
    rap_men_animate_rapper ANIM_HONTO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    clear_text_f
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_women_kare_ni_wa_naisho
    play_sfx_localized s_f_rapW_v_KareniwaNaisho_seqData, s_f_rapW_v_KareniwaNaisho_en_seqData
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    spawn_cue CUE_UUN
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 0
    print_text_f text_rap_women_oyatsu_desu_ka
    play_sfx_localized s_f_rapW_v_YoOyatuDesuka_seqData, s_f_rapW_v_YoOyatuDesuka_en_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 0
    print_text_f text_rap_women_juji_desu_ka
    play_sfx_localized s_f_rapW_v_Yo10JiDesuka_seqData, s_f_rapW_v_Yo10JiDesuka_en_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 1
    print_text_f text_rap_women_tabeteii_kamo_ne
    play_sfx_localized s_f_rapW_v_TabeteIikamone_seqData, s_f_rapW_v_TabeteIikamone_en_seqData
    rap_men_animate_rapper ANIM_HONTO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    clear_text_f
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    spawn_cue CUE_UN
    set_marking_criteria 0
    print_text_f text_rap_women_naisho_desu_ka
    beat_anim
    rest 24
    rest 12
    rest 6
    play_sfx_localized s_f_rapW_v_Naishodesuka_seqData, s_f_rapW_v_Naishodesuka_en_seqData
    rap_men_animate_rapper ANIM_HONTO
    rest 6
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 0
    print_text_f text_rap_women_oyatsu_desu_ka
    play_sfx_localized s_f_rapW_v_YoOyatuDesuka_seqData, s_f_rapW_v_YoOyatuDesuka_en_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 0
    print_text_f text_rap_women_juji_desu_ka
    play_sfx_localized s_f_rapW_v_Yo10JiDesuka_seqData, s_f_rapW_v_Yo10JiDesuka_en_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_women_kare_ni_wa_naisho
    play_sfx_localized s_f_rapW_v_KareniwaNaisho_seqData, s_f_rapW_v_KareniwaNaisho_en_seqData
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    spawn_cue CUE_UUN
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest_localized 24, 16
    play_sfx_localized s_f_rapW_v_OyatuwaSaiko_seqData, s_f_rapW_v_OyatuwaSaiko_en_seqData
    rest_localized 0, 8
    set_marking_criteria 2
    print_text_f text_rap_women_oyatsu_wa_saikou
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    spawn_cue CUE_UUN
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 1
    print_text_f text_rap_women_kare_no_oyatsu_da_ne
    play_sfx_localized s_f_rapW_v_KarenoOyatudane_seqData, s_f_rapW_v_KarenoOyatudane_en_seqData
    rap_men_animate_rapper ANIM_HONTO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    clear_text_f
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 1
    print_text_f text_rap_women_aketeii_kamo_ne
    play_sfx_localized s_f_rapW_v_AketeIikamone_seqData, s_f_rapW_v_AketeIikamone_en_seqData
    rap_men_animate_rapper ANIM_HONTO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    clear_text_f
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 1
    print_text_f text_rap_women_tabeteii_kamo_ne
    play_sfx_localized s_f_rapW_v_TabeteIikamone_seqData, s_f_rapW_v_TabeteIikamone_en_seqData
    rap_men_animate_rapper ANIM_HONTO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    clear_text_f
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    spawn_cue CUE_UN
    set_marking_criteria 0
    print_text_f text_rap_women_naisho_desu_ka
    beat_anim
    rest 24
    rest 12
    rest 6
    play_sfx_localized s_f_rapW_v_Naishodesuka_seqData, s_f_rapW_v_Naishodesuka_en_seqData
    rap_men_animate_rapper ANIM_HONTO
    rest 6
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest_localized 24, 16
    play_sfx_localized s_f_rapW_v_OyatuwaSaiko_seqData, s_f_rapW_v_OyatuwaSaiko_en_seqData
    rest_localized 0, 8
    set_marking_criteria 2
    print_text_f text_rap_women_oyatsu_wa_saikou
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    spawn_cue CUE_UUN
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_women_amakute_saikou
    play_sfx_localized s_f_rapW_v_AmakuteSaiko_seqData, s_f_rapW_v_AmakuteSaiko_en_seqData
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    spawn_cue CUE_UUN
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_women_kibun_wa_saikou
    play_sfx_localized s_f_rapW_v_KibunnwaSaiko_seqData, s_f_rapW_v_KibunnwaSaiko_en_seqData
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    spawn_cue CUE_UUN
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_women_betsubara_saikou
    play_sfx_localized s_f_rapW_v_BetubaraSaiko_seqData, s_f_rapW_v_BetubaraSaiko_en_seqData
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    spawn_cue CUE_UUN
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_women_kare_ni_wa_naisho
    play_sfx_localized s_f_rapW_v_KareniwaNaisho_seqData, s_f_rapW_v_KareniwaNaisho_en_seqData
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    spawn_cue CUE_UUN
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_women_dare_ni_mo_naisho
    play_sfx_localized s_f_rapW_v_DarenimoNaisho_seqData, s_f_rapW_v_DarenimoNaisho_en_seqData
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    spawn_cue CUE_UUN
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest_localized 24, 16
    play_sfx_localized s_f_rapW_v_OyatuwaSaiko_seqData, s_f_rapW_v_OyatuwaSaiko_en_seqData
    rest_localized 0, 8
    set_marking_criteria 2
    print_text_f text_rap_women_oyatsu_wa_saikou
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    spawn_cue CUE_UUN
    clear_text_f
    beat_anim
    rest 24
    rest 24
    print_text_f text_rap_women_naisho_desu_ka
    beat_anim
    rest 24
    rest 12
    rest 6
    play_sfx_localized s_f_rapW_v_Naishodesuka_seqData, s_f_rapW_v_Naishodesuka_en_seqData
    rap_men_animate_rapper ANIM_HONTO
    rest 6
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    play_sfx_localized s_f_rapW_v_Yeah_seqData, s_f_rapW_v_Yeah_en_seqData
    rap_men_animate_rapper ANIM_KAMONE
    rest 24
    beat_anim
    rest 24
    rest 24
    print_text_f D_08067d90
    stop_tracking_perfect_campaign
    beat_anim
    rest 24
    rest 24
    mod_music_volume 0, 120
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    disable_pause_menu
    rest 24
return

.end
